name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bantr
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run demos:unzip
      # Run DB migration script
      - run: npm explore @bantr/lib -- npm run db:migrate
      - run: npm test
        env:
          CI: true
          BANTR_IS_TEST: true
          BANTR_PG_USER: postgres
          BANTR_PG_PW: postgres
          BANTR_PG_DB: bantr
          BANTR_PG_HOST: localhost
          BANTR_PG_PORT: 5432
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 563aebb42b3b2aa2d48cb522008b8c7222674a572abd8120fd799d35ef8d8620
          CI: true
          BANTR_IS_TEST: true
          BANTR_PG_USER: postgres
          BANTR_PG_PW: postgres
          BANTR_PG_DB: bantr
          BANTR_PG_HOST: localhost
          BANTR_PG_PORT: 5432
        with:
          coverageCommand: npm run test:cov
          debug: true
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
